=== Concepts

[[bucket, Bucket]]
==== Bucket
`Bucket` is a rate-limiter that is implemented on the top of ideas of well-known https://en.wikipedia.org/wiki/Token_bucket[Token Bucket algorithm].
In the Bucket4j library code the `Bucket` is represented by interface https://github.com/bucket4j/bucket4j/blob/{minor-number}/bucket4j-core/src/main/java/io/github/bucket4j/Bucket.java[io.github.bucket4j.Bucket].

.Bucket aggregates the following parts:
* <<bucket-bonfiguration>> specifies an immutable collection of limitation rules that are used by the bucket during its work.
* <<bucket-state>> the place where bucket stores mutable state like the amount of currently available tokens.

A bucket can be constructed via a special builder API <<local-bucket-builder>> that is available by factory method:
[source, java]
----
Bucket bucket = Bucket.builder()
   .addLimit(...)
   .build();
----

[[bucket-bonfiguration, BucketConfiguration]]
==== BucketConfiguration
`BucketConfiguration` can be described as collection of <<bandwidth, limits>> that are used by <<bucket>> during its job. Configuration
In the Bucket4j library code the `BucketConfiguration` is represented by class https://github.com/bucket4j/bucket4j/blob/{minor-number}/bucket4j-core/src/main/java/io/github/bucket4j/BucketConfiguration.java[io.github.bucket4j.BucketConfiguration]. Configuration is immutable, there is no way to add or remove a limit to already created configuration. However, you can replace the configuration of the bucket via creating a new configuration instance and calling `bucket.replaceConfiguration(newConfiguration)`.

Usually, you should not create BucketConfiguration directly(excepting the case with configuration replacement) because <<local-bucket-builder>> does for you behind the scene, for rare cases when you need to create configuration directly you have to use `ConfigurationBuilder` that is available by factory method:
[source, java]
----
BucketConfiguration configuration = BucketConfiguration.builder()
    .addLimit(...)
    .build()
----

IMPORTANT: Most users configure a single limit per configuration, but it is strongly recommended to analyze whether <<short-timed-bursts, short-timed bursts problem>>
can affect your application and if so then think about adding more limits.

[[bandwidth]]
==== Limitation/Bandwidth
Limitations that are used by bucket can be denoted in terms of bandwidths. Bandwidth is denoted by the following terms:

Capacity::
`Capacity` is the term that is directly inherited from the classic interpretation of the token-bucket algorithm, this specifies how many tokens your bucket has. Refill must be configured during building stage
Capacity must be configured during building stage
[source, java]
----
Bucket bucket = Bucket.builder()
    .addLimit(limit -> limit.capacity(42))
    .build()
----

Refill::
Refill specifies how fast tokens can be refilled after it was consumed from a bucket.
Refill must be configured during building stage
[source, java]
----
Bucket bucket = Bucket.builder()
    .addLimit(limit -> limit.capacity(...).refillXXX(...)) // where XXX - is concrete refill style
    .build()
----
Bucket4j allows to choose different <<refill-types>>.

Initial tokens::
Bucket4j extends the token-bucket algorithm by allowing to specify the initial amount of tokens for each bandwidth. By default, an initial amount of tokens equals to capacity and can be changed by `withInitialTokens` method: +
+
[source, java]
----
Bucket bucket = Bucket.builder()
    .addLimit(limit -> limit.capacity(42).refillGreedy(1, ofSeconds(1)).initialTokens(13))
    .build()
----

Bandwidth ID::
The identifier is the optional attribute that is null by default. You may prefer to assign identifiers for bandwidths if you use on-the-fly configuration replacement and your buckets have more than one bandwidth per bucket, otherwise, it is better to avoid using identifiers to preserve memory.
The Identifier for bandwidth can be specified in following way: +
+
[source, java]
----
BucketConfiguration configuration = BucketConfiguration.builder()
    .addLimit(limit -> limit.capacity(1000).refillGreedy(1000, ofMinutes(1)).id("business-limit"))
    .addLimit(limit -> limit.capacity(100).refillGreedy(100, ofSeconds(1)).id("burst-protection"))
    .build();
----
NOTE: Identifiers are critical for on-the-fly configuration replacement functionality because during replacement it needs to decide how correctly propagate information about already consumed tokens from the state before config replacement to the state after replacement. This is not a trivial task especially when the number of limits is changing.

[[refill-types, Refill types]]
==== Refill styles
Bucket4j allows to choose different styles in which consumed tokens are being refilled to bucket

.There are four types of refill:
Greedy::
This type of refill greedily regenerates tokens manner, it tries to add the tokens to the bucket as soon as possible. For example refill "10 tokens per 1 second" adds 1 token per every 100 milliseconds, in other words, the refill will not wait 1 second to regenerate a bunch of 10 tokens. The three refills below do refill of tokens with the same speed: +
+
[source, java]
----
Bucket.builder().addLimit(limit -> limit.capacity(1000).refillGreedy(600, ofMinutes(1)))
Bucket.builder().addLimit(limit -> limit.capacity(1000).refillGreedy(10, ofSeconds(1)))
Bucket.builder().addLimit(limit -> limit.capacity(1000).refillGreedy(1, ofMillis(100)))
----

Intervally::
This type of refill regenerates tokens in an interval manner. "Interval" in opposite to "greedy"  will wait until the whole period will be elapsed before regenerating the whole amount of tokens. +
+
.Example: +
+
[source, java]
----
// refills 100 tokens each minute
Bucket bucket = Bucket.builder().addLimit(limit -> limit.capacity(1000).refillIntervally(100, ofMinutes(1))).build();
----

IntervallyAligned::
This type of refill regenerates that does refill of tokens in an interval manner. Interval" in opposite to "greedy"  will wait until the whole period will be elapsed before regenerating the whole amount of tokens. In addition to *Interval* it is possible to specify the time when the first refill should happen.  This type can be used to configure clear interval boundary i.e. start of the second, minute, hour, day.
+
.Example:
[source, java]
----
// imagine that wall clock is 16:20, the first refill will happen at 17:00
// first refill will happen in the beginning of next hour
Instant firstRefillTime = ZonedDateTime.now()
  .truncatedTo(ChronoUnit.HOURS)
  .plus(1, ChronoUnit.HOURS)
  .toInstant();

Bucket bucket = Bucket.builder().addLimit(limit -> limit.capacity(400).refillIntervallyAligned(400, ofHours(1), firstRefillTime)).build();
----

RefillIntervallyAlignedWithAdaptiveInitialTokens::
See javadocs.


[[bucket-state, BucketState]]
==== BucketState
BucketState is the place where bucket stores own mutable state like:

* Amount of currently available tokens.
* Timestamp when the last refill was happen.

`BucketState` is represented by interface https://github.com/bucket4j/bucket4j/blob/{minor-number}/bucket4j-core/src/main/java/io/github/bucket4j/Bucket.java[io.github.bucket4j.BucketState]. Usually you never interact with this interface, excepting the cases when you want to get access to low-level diagnostic API that is described in


[[local-bucket-builder, BucketBuilder]]
==== BucketBuilder
It was explicitly decided by library authors to not provide for end-users to construct a library entity via direct constructors.

.It was to reason to split built-time and usage-time APIs:
* To be able in the future to change internal implementations without breaking backward compatibility.
* To provide `Fluent Builder API` that in our minds is a good modern library design pattern.

`LocalBucketBuilder` is a fluent builder that is specialized to construct the local buckets, where a local bucket is a bucket that holds an internal state just in memory and does not provide clustering functionality. Bellow an example of LocalBucketBuilder usage:
[source, java]
----
Bucket bucket = Bucket.builder()
    .addLimit(...)
    .withNanosecondPrecision()
    .withSynchronizationStrategy(SynchronizationStrategy.LOCK_FREE)
    .build()
----