[[configuration-replacement]]
=== On-the-fly configuration replacement
As mentioned in the definition of <<bucket-configuration>>, a configuration is an immutable object.
You cannot add, remove, or change the limits of an already-created configuration. However, you can replace the configuration of a bucket by creating a new configuration instance and calling `bucket.replaceConfiguration(newConfiguration, tokensInheritanceStrategy)`.

==== Why configuration replacement is not trivial
1. The first problem with configuration replacement is deciding how to carry over the available tokens from the bucket's previous configuration to its new one. If you do not care about the previous bucket state, use <<tokens-inheritance-strategy-reset,TokensInheritanceStrategy.RESET>>. But the problem becomes tricky when previous consumption (not yet compensated by a refill) should still have an effect on the bucket under the new configuration. In that case, you need to choose between:
* <<tokens-inheritance-strategy-proportionally, TokensInheritanceStrategy.PROPORTIONALLY>>
* <<tokens-inheritance-strategy-as-is, TokensInheritanceStrategy.AS_IS>>
* <<tokens-inheritance-strategy-additive, TokensInheritanceStrategy.ADDITIVE>>

2. There is a second problem when you choose <<tokens-inheritance-strategy-proportionally, PROPORTIONALLY>>, <<tokens-inheritance-strategy-as-is, AS_IS>>, or <<tokens-inheritance-strategy-additive, ADDITIVE>> and the bucket has more than one bandwidth. For example, how should `replaceConfiguration` match up the old and new bandwidths in the example below?
+
[source, java]
----
Bucket bucket = Bucket.builder()
    .addLimit(limit -> limit.capacity(10).refillGreedy(10, ofSeconds(1)))
    .addLimit(limit -> limit.capacity(10000).refillGreedy(10000, ofHours(1)))
    .build();
    ...
BucketConfiguration newConfiguration = BucketConfiguration.builder()
    .addLimit(limit -> limit.capacity(5000).refillGreedy(5000, ofHours(1)))
    .addLimit(limit -> limit.capacity(100).refillGreedy(100, ofSeconds(10)))
    .build();
bucket.replaceConfiguration(newConfiguration, TokensInheritanceStrategy.AS_IS);
----
+
A naive strategy - copying tokens by bandwidth index - clearly does not work well here, because the result would depend entirely on the order in which bandwidths happen to be listed in the old and new configurations.

==== Taking control of the replacement process via bandwidth identifiers
Instead of relying on fragile positional matching, Bucket4j lets you keep control of this process by assigning identifiers to bandwidths,
so that in the case of multiple bandwidths, the replacement code can copy available tokens by bandwidth ID. It is better to rewrite the code above as follows:
[source, java]
----
    Bucket bucket = Bucket.builder()
         .addLimit(limit -> limit.capacity(10).refillGreedy(10, ofSeconds(1)).id("technical-limit"))
         .addLimit(limit -> limit.capacity(10000).refillGreedy(10000, ofHours(1)).id("business-limit"))
         .build();
     ...
     BucketConfiguration newConfiguration = BucketConfiguration.builder()
         .addLimit(limit -> limit.capacity(100).refillGreedy(100, ofSeconds(10)).id("technical-limit"))
         .addLimit(limit -> limit.capacity(5000).refillGreedy(5000, ofHours(1)).id("business-limit"))
         .build();
     bucket.replaceConfiguration(newConfiguration, TokensInheritanceStrategy.PROPORTIONALLY);
----
.The following rules apply to bandwidth identifiers:
* By default, a bandwidth has a *null* identifier.
* A `null` identifier is only considered equal to another `null` identifier if there is exactly one bandwidth with a `null` identifier in the bucket.
* If an identifier is specified for a bandwidth, it must be unique within the bucket - Bucket4j does not allow creating several bandwidths with the same ID.

==== TokensInheritanceStrategy explanation
`TokensInheritanceStrategy` specifies the rules for carrying over available tokens during the configuration-replacement process.

.There are four strategies:

[[tokens-inheritance-strategy-reset]]
RESET::
Use this mode when you want to simply forget the previous bucket state. `RESET` instructs Bucket4j to erase all previous state. Using this strategy is equivalent to removing the bucket and creating it again with the new configuration.

[[tokens-inheritance-strategy-proportionally]]
PROPORTIONALLY::
Copies available tokens proportionally to the change in bandwidth capacity, using the following formula: *newAvailableTokens = availableTokensBeforeReplacement * (newBandwidthCapacity / capacityBeforeReplacement)*
+
.PROPORTIONALLY strategy examples:
** *Example 1:* imagine a bandwidth created with `Bandwidth.builder().capacity(100).refillGreedy(10, ofMinutes(1)).build()`. +
+
At the moment of configuration replacement, there were 40 available tokens. +
+
After replacing this bandwidth with `Bandwidth.builder().capacity(200).refillGreedy(10, ofMinutes(1)).build()`, the 40 available tokens are multiplied by 2 (200/100), so after replacement we have 80 available tokens.

** *Example 2:* imagine a bandwidth created with `Bandwidth.builder().capacity(100).refillGreedy(10, ofMinutes(1)).build()`.
At the moment of configuration replacement, there were 40 available tokens. After replacing this bandwidth with `Bandwidth.builder().capacity(20).refillGreedy(10, ofMinutes(1)).build()`, the 40 available tokens are multiplied by 0.2 (20/100), so after replacement we have 8 available tokens.

[[tokens-inheritance-strategy-as-is]]
AS_IS::
Copies available tokens as-is, with one exception: if the number of available tokens is greater than the new capacity, it is reduced to the new capacity.
+
.AS_IS strategy examples:
** *Example 1:* imagine a bandwidth created with `Bandwidth.builder().capacity(100).refillGreedy(10, ofMinutes(1)).build()`. +
+
At the moment of configuration replacement, there were 40 available tokens. +
+
After replacing this bandwidth with `Bandwidth.builder().capacity(200).refillGreedy(10, ofMinutes(1)).build()`, the 40 available tokens are simply copied, so after replacement we have 40 available tokens.

** *Example 2:* imagine a bandwidth created with `Bandwidth.builder().capacity(100).refillGreedy(10, ofMinutes(1)).build()`. +
+
At the moment of configuration replacement, there were 40 available tokens. +
+
After replacing this bandwidth with `Bandwidth.builder().capacity(20).refillGreedy(10, ofMinutes(1)).build()`, the 40 available tokens cannot be copied as-is because they exceed the new capacity, so available tokens are reduced to 20.

[[tokens-inheritance-strategy-additive]]
ADDITIVE::
Copies available tokens as-is, with one exception: if the new bandwidth capacity is greater than the old capacity, the available tokens are increased by the difference between the old and the new capacity. +
+
*The formula is:* +
`newAvailableTokens = Math.min(availableTokensBeforeReplacement, newBandwidthCapacity) + Math.max(0, newBandwidthCapacity - capacityBeforeReplacement)` +
+
.ADDITIVE strategy examples:
** *Example 1:* imagine a bandwidth created with `Bandwidth.builder().capacity(100).refillGreedy(10, ofMinutes(1)).build()`. +
+
At the moment of configuration replacement, there were 40 available tokens. +
+
After replacing this bandwidth with `Bandwidth.builder().capacity(200).refillGreedy(200, ofMinutes(1)).build()`, the 40 available tokens are copied and increased by the difference between the old and new capacity, so after replacement we have 140 available tokens.

** *Example 2:* imagine a bandwidth created with `Bandwidth.builder().capacity(100).refillGreedy(10, ofMinutes(1)).build()`. +
+
At the moment of configuration replacement, there were 40 available tokens. +
+
After replacing this bandwidth with `Bandwidth.builder().capacity(20).refillGreedy(10, ofMinutes(1)).build()`,
after replacement we have 20 available tokens.

** *Example 3:* imagine a bandwidth created with `Bandwidth.builder().capacity(100).refillGreedy(10, ofMinutes(1)).build()`. +
+
At the moment of configuration replacement, there were 10 available tokens.
+
After replacing this bandwidth with `Bandwidth.builder().capacity(100).refillGreedy(20, ofMinutes(1)).build()`, after replacement we have 10 available tokens.
