=== Listening for bucket events

==== What can be listened
.You can attach a listener to bucket by to track following events:
- When tokens are consumed from a bucket.
- When consumption requests were rejected by the bucket.
- When the thread was parked to wait for tokens refill as a result of interaction with ``BlockingBucket``.
- When the thread was interrupted during the wait for tokens to be refilled as a result of interaction with ``BlockingBucket``.
- When a delayed task was submitted to ``ScheduledExecutorService`` as a result of interaction with ``AsyncScheduledBucket``.

==== Listener API - corner cases
========
**Question:** How many listeners are needed to create an application that uses many buckets?

**Answer:**  it depends:

- If you want to have aggregated statistics for all buckets then create a single listener per application and reuse this listener for all buckets.
- If you want to measure statistics independently per bucket then use a listener per bucket model.
========

========
**Question:** where are methods the listener is invoking in case of distributed usage?

**Answer:** listener always invoked on the client-side, which means that each client JVM will have its independent stat for the same bucket.
========

========
**Question:** Why does bucket invoke the listener on the client-side instead of the server-side in case of distributed scenario? What do I need to do if I need an aggregated stat across the whole cluster?

**Answer:** Because of a planned expansion to non-JVM back-ends such as Redis, MySQL, PostgreSQL.
It is not possible to serialize and invoke listener on this non-java back-ends, so it was decided to invoke listener on the client-side,
to avoid inconsistency between different back-ends in the future.
You can do post-aggregation of monitoring statistics via features built into your monitoring database or via mediator(like StatsD) between your application and the monitoring database.
========

==== Specify listener to local bucket at build time
[source, java]
----
BucketListener listener = new MyListener();

Bucket bucket = Bucket.builder()
    .addLimit(limit -> limit,capacity(100).refillGreedy(100, ofMinutes(1)))
    .withListener(listener)
    .build()
----

==== Specify listener to distributed bucket at build time
[source, java]
----
BucketListener listener = new MyListener();

Bucket bucket = proxyManager.builder()
     .withListener(listener)
     .build(key, configSupplier);
----

==== Specify listener to async distributed bucket at build time
[source, java]
----
BucketListener listener = new MyListener();

AsyncBucketProxy bucket = proxyManager.asAsync().builder()
     .withListener(listener)
     .build(key, configSupplier);
----

==== Specify listener to distributed bucket at proxy-manager build time
You can configure default listener at proxy-manager build time. And this listener will be used for all bucket that belong to this proxy-manager.
Bellow example for Hazelcast, the way to configure listener for other backends is the same.
[source, java]
----
BucketListener listener = new MyListener();

// listener will be attached to all buckets that belong to this proxy manager
HazelcastLockBasedProxyManager proxyManager = Bucket4jHazelcast.entryProcessorBasedBuilder(map)
    .defaultListener(listener)
    .build();
----

==== Specify listener to bucket at use time.
Sometimes listener is not known at bucket build time, and you want to clarify listener later.
For example it can happen when you want to share same bucket per multiple users,
but in same time it needs to have dedicated listener per each user.

In such case you can build bucket without listener and attach it later via the ``toListenable`` method,
this way will create a decorator to original bucket
[source, java]
----

public void doSomethingProtected(User user, Bucket bucket) {
    bucket = decorate(user, bucket).tryConsume(1)
    if (bucket.tryConsume(1)) {
        doSomething(user);
    } else {
        handleRateLimitError(user);
    }
}

...
private Bucket decorate(User user, Bucket originalbucket) {
    BucketListener listener = new BucketListener() {
        @Override
        public void onConsumed(long tokens) {
            // log something related for user or increase user related metrics
        }
        @Override
        public void onRejected(long tokens) {
            // log something related for user or increase user related metrics
        }
        ...
    }
    return originalbucket.toListenable(listener);
}
----

==== Example of integration with Dropwizard metrics-core
`io.github.bucket4j.SimpleBucketListener` is a simple implementation of `io.github.bucket4j.BucketListener` interface that is available out of the box. Below is the example of exposing statistics via Dropwizard Metrics(for Micrometer it should be quite similar):
[source, java]
----
public static Bucket decorateBucketByStatListener(Bucket originalBucket, String bucketName, MetricRegistry registry) {
  SimpleBucketListener stat = new SimpleBucketListener();
  registry.register(name + ".consumed", (Gauge<Long>) stat::getConsumed);
  registry.register(name + ".rejected", (Gauge<Long>) stat::getRejected);
  registry.register(name + ".parkedNanos", (Gauge<Long>) stat::getParkedNanos);
  registry.register(name + ".interrupted", (Gauge<Long>) stat::getInterrupted);
  registry.register(name + ".delayedNanos", (Gauge<Long>) stat::getDelayedNanos);

  return originalBucket.toListenable(stat);
}
----
