[[verbose-api, Verbose/Debug API]]
=== Verbose/Debug API
Verbose API:: is an API whose purpose is to attach low-level diagnostic information to the result of any interaction with a bucket. It provides the same functionality as the regular API, with one difference - the result of any method is always wrapped in a `VerboseResult`.

VerboseResult:: is a wrapper around an interaction result that also carries a snapshot of the bucket and its configuration, as they were at the moment of the interaction.

==== Verbose API entry points
The way to access the `Verbose API` is the same for every kind of bucket - just call the `asVerbose()` method:

[source, java]
----
// for io.github.bucket4j.Bucket
Bucket bucket = ...;
VerboseBucket verboseBucket = bucket.asVerbose();
VerboseSchedulingBucket verboseSchedulingBucket = bucket.asScheduler().asVerbose();
VerboseBlockingBucket verboseBlockingBucket = bucket.asBlocking().asVerbose();
----
[source, java]
----
// for io.github.bucket4j.distributed.AsyncBucketProxy
AsyncBucketProxy bucket = ...;
AsyncVerboseBucket verboseBucket = bucket.asVerbose();
VerboseSchedulingBucket verboseSchedulingBucket = bucket.asScheduler().asVerbose();
----

==== Principles of result decoration
* A `void` return type is always wrapped as `VerboseResult<Void>`.
* A primitive result type such as `long` or `boolean` is always wrapped using the corresponding boxed type, for example `VerboseResult<Boolean>`.
* A non-primitive result type is always wrapped as-is, for example `VerboseResult<EstimationProbe>`.

==== Example of Verbose API usage
[source, java]
----
VerboseResult<ConsumptionProbe> verboseResult = bucket.asVerbose().tryConsumeAndReturnRemaining(numberOfTokens);

BucketConfiguration bucketConfiguration = verboseResult.getConfiguration();
long capacity = Arrays.stream(bucketConfiguration.getBandwidths())
                .mapToLong(Bandwidth::getCapacity)
                .max().getAsLong();
response.addHeader("RateLimit-Limit", "" + capacity);

VerboseResult.Diagnostics diagnostics = verboseResult.getDiagnostics();
response.addHeader("RateLimit-Remaining", "" + diagnostics.getAvailableTokens());
response.addHeader("RateLimit-Reset", "" + TimeUnit.NANOSECONDS.toSeconds(diagnostics.calculateFullRefillingTime()));

ConsumptionProbe probe = verboseResult.getValue();
if (probe.isConsumed()) {
    // the limit is not exceeded
    filterChain.doFilter(servletRequest, servletResponse);
} else {
    // limit is exceeded
    HttpServletResponse httpResponse = (HttpServletResponse) servletResponse;
    httpResponse.setStatus(429);
    httpResponse.setContentType("text/plain");
    httpResponse.getWriter().append("Too many requests");
}
----
