=== JDBC integrations
General principles for using each JDBC integration:

* Bucket4j does not create the bucket storage table for you - you need to create it yourself.
A DDL example is provided for each integration.
* Relational databases are not in-memory data grids and have no built-in TTL support, so you should create a trigger or a scheduler to clear expired rows from your bucket storage table.

==== Overriding the table and column naming scheme
.There are three naming parameters
* `tableName` - name of the table used as the bucket store. Default value is `bucket`
* `idColumnName` - name of the primary key column. Default value is `id`
* `stateColumnName` - name of the column used to store the bucket state. Default value is `state`

You can override the naming as you wish at proxy-manager build time. Below is an example for MySQL;
the code for other integrations is the same.

[source, java]
----
MySQLSelectForUpdateBasedProxyManager<Long> proxyManager = Bucket4jMySQL
    .selectForUpdateBasedBuilder(dataSource)
    .table("user_buckets")
    .idColumn("user_id")
    .stateColumn("state_bytes")
    .build()
----

==== Overriding the type of the primary key
By default, `java.lang.Long` is used as the Java representation of the primary-key column value,
and the primary key column type is expected to be assignable from `Long` when binding `PreparedStatement` parameters. +

Sometimes you need the primary key column to use a different type, for example `java.lang.String` and its corresponding database type.
You can configure a custom primary-key type at proxy-manager build time. Below is an example for PostgreSQL;
the code for other integrations is the same.
[source,sql]
----
CREATE TABLE IF NOT EXISTS bucket(id VARCHAR PRIMARY KEY, state BYTEA);
----
[source, java]
----
PostgreSQLSelectForUpdateBasedProxyManager<String> proxyManager = Bucket4jPostgreSQL
    .selectForUpdateBasedBuilder(dataSource)
    .primaryKeyMapper(PrimaryKeyMapper.STRING)
    .build();
----
There are several predefined mappers defined inside `io.github.bucket4j.distributed.jdbc.PrimaryKeyMapper`;
if none of them suit your needs, you can define your own by implementing this interface.

==== Expiration policy
Relational databases have no built-in auto-expiration functionality, unlike, for example, Redis.
For all JDBC integrations, Bucket4j only calculates the `expires_at` column if an expiration policy is configured.
You then need to manually trigger the removal of expired buckets, as shown below.
[source,sql]
----
CREATE TABLE IF NOT EXISTS bucket(id BIGINT PRIMARY KEY, state BYTEA, expires_at BIGINT);
----
[source, java]
----
PostgreSQLSelectForUpdateBasedProxyManager<Long> proxyManager = Bucket4jPostgreSQL
    .selectForUpdateBasedBuilder(dataSource)
    .expirationAfterWrite(basedOnTimeForRefillingBucketUpToMax(Duration.ofSeconds(60)))
    .build();

private static final int MAX_TO_REMOVE_IN_ONE_TRANSACTION = 1_000;
private static final int THRESHOLD_TO_CONTINUE_REMOVING = 50;

// once per day at 4:30 morning
@Scheduled(cron = "0 30 4 * * *")
public void scheduleFixedDelayTask() {
    int removedCount;
    do {
        removedCount = proxyManager.removeExpired(MAX_TO_REMOVE_IN_ONE_TRANSACTION);
        if (removedCount > 0) {
            logger.info("Removed {} expired buckets", removedCount);
        } else {
            logger.info("There are no expired buckets to remove");
        }
   } while (removedCount > THRESHOLD_TO_CONTINUE_REMOVING);
}
----

include::postgresql.adoc[]

include::mysql.adoc[]

include::mariadb.adoc[]

include::oracle.adoc[]

include::mssql.adoc[]

include::db2.adoc[]

