[[bucket4j-postgresql, Bucket4j-Postgresql]]
==== PostgreSQL integration
===== Dependencies
To use the Bucket4j extension for PostgreSQL, add the following dependency:
[source, xml, subs=attributes+]
----
<dependency>
    <groupId>com.bucket4j</groupId>
    <artifactId>bucket4j_jdk17-postgresql</artifactId>
    <version>{revnumber}</version>
</dependency>
----

===== DDL example
[source,sql]
----
// if the expiration feature is not required
CREATE TABLE IF NOT EXISTS bucket(id BIGINT PRIMARY KEY, state BYTEA);
----
[source,sql]
----
// if the expiration feature is required for PostgreSQLSelectForUpdateBasedProxyManager
CREATE TABLE IF NOT EXISTS bucket(id BIGINT PRIMARY KEY, state BYTEA, expires_at BIGINT);
----
[source,sql]
----
// if the expiration feature is required for PostgreSQLAdvisoryLockBasedProxyManager
CREATE TABLE IF NOT EXISTS bucket(id BIGINT PRIMARY KEY, state BYTEA, expires_at BIGINT, explicit_lock BIGINT);
----

===== PostgreSQLSelectForUpdateBasedProxyManager
`PostgreSQLSelectForUpdateBasedProxyManager` is based on the standard SQL `SELECT FOR UPDATE` syntax.
This prevents the selected rows from being modified or deleted by other transactions until the current transaction ends.
That is, any other transaction that attempts to `UPDATE`, `DELETE`, or `SELECT FOR UPDATE` these rows will be blocked until the current transaction ends.
Also, if an `UPDATE`, `DELETE`, or `SELECT FOR UPDATE` from another transaction has already locked a selected row, `SELECT FOR UPDATE` will wait for the other transaction to complete, and will then lock and return the updated row (or no row, if the row was deleted).
Within a `SERIALIZABLE` transaction, however, an error will be thrown if a row to be locked has changed since the transaction started.
[source, java]
----
PostgreSQLSelectForUpdateBasedProxyManager<Long> proxyManager = Bucket4jPostgreSQL
    .selectForUpdateBasedBuilder(dataSource)
    .build();
...
Long key = 1L;
BucketConfiguration bucketConfiguration = BucketConfiguration.builder()
    .addLimit(limit -> limit.capacity(10).refillGreedy(10, ofSeconds(1)))
    .build();
BucketProxy bucket = proxyManager.getProxy(key, () -> bucketConfiguration);
----

===== PostgreSQLAdvisoryLockBasedProxyManager
`PostgreSQLadvisoryLockBasedProxyManager` is based on `pg_advisory_xact_lock`, which locks an application-defined resource that can be identified either by a single 64-bit key value or two 32-bit key values (note that these two key spaces do not overlap).
If another session already holds a lock on the same resource identifier, this function will wait until the resource becomes available.
The lock is exclusive.
Multiple lock requests stack, so if the same resource is locked three times, it must then be unlocked three times before it becomes available to other sessions.
The lock is automatically released at the end of the current transaction and cannot be released explicitly.

[source, java]
----
PostgreSQLadvisoryLockBasedProxyManager<Long> proxyManager = Bucket4jPostgreSQL
    .advisoryLockBasedBuilder(dataSource)
    .build();
...
Long key = 1L;
BucketConfiguration bucketConfiguration = BucketConfiguration.builder()
    .addLimit(limit -> limit.capacity(10).refillGreedy(10, ofSeconds(1)))
    .build();
BucketProxy bucket = proxyManager.getProxy(key, () -> bucketConfiguration);
----