[[bucket4j-coherence, Bucket4j-Coherence]]
==== Oracle Coherence integration
===== Dependencies
To use the Bucket4j extension with a current version of Oracle Coherence, add the following dependency:
[source, xml, subs=attributes+]
----
<dependency>
    <groupId>com.bucket4j</groupId>
    <artifactId>bucket4j_jdk17-coherence</artifactId>
    <version>{revnumber}</version>
</dependency>
----
If you are using a legacy ``Coherence 21.x`` release, add this dependency instead:
[source, xml, subs=attributes+]
----
<dependency>
    <groupId>com.bucket4j</groupId>
    <artifactId>bucket4j_jdk17-coherence-21</artifactId>
    <version>{revnumber}</version>
</dependency>
----

===== General compatibility matrix principles
* Bucket4j's authors do not continuously monitor new Coherence releases, so there can be periods when no Bucket4j version is compatible with a newly released Coherence version.
Log an issue in the https://github.com/bucket4j/bucket4j/issues[bug tracker] if you hit this - adding support for a new Coherence version is usually an easy fix.
* Integrations with legacy Coherence versions are not removed without a clear reason. Even if you work at a large enterprise that does not update its infrastructure often, you still get Bucket4j's new features on legacy Coherence releases.

===== Example of Bucket instantiation
[source, java]
----
com.tangosol.net.NamedCache<K, byte[]> cache = ...;
private static final CoherenceProxyManager<K> proxyManager = Bucket4jCoherence
    .entryProcessorBasedBuilder(cache)
     // setup optional parameters if necessary
    .build();

...
BucketConfiguration configuration = BucketConfiguration.builder()
    .addLimit(limit -> limit.capacity(1_000).refillGreedy(1_000, ofMinutes(1)))
    .build();

Bucket bucket = proxyManager.getProxy(key, () -> configuration);
----

===== Configuring POF serialization for Bucket4j library classes
If you configure nothing, Bucket4j library classes are serialized using plain Java serialization by default, which can be rather slow and should generally be avoided.
``Bucket4j`` provides https://docs.oracle.com/cd/E24290_01/coh.371/e22837/api_pof.htm#COHDG1363[custom POF serializers] for all library classes that can be transferred over the network.
To let Coherence know about the POF serializers, register the serializer in the POF configuration file:
====
``io.github.bucket4j.grid.coherence.pof.CoherenceEntryProcessorPofSerializer`` for class ``io.github.bucket4j.grid.coherence.CoherenceProcessor``
====

.Example of POF serialization config:
[,xml]
----
<pof-config xmlns="http://xmlns.oracle.com/coherence/coherence-pof-config"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-pof-config coherence-pof-config.xsd">

    <user-type-list>
        <!-- Include default Coherence types -->
        <include>coherence-pof-config.xml</include>

        <!-- Define serializers for Bucket4j classes -->
        <user-type>
            <type-id>1001</type-id>
            <class-name>io.github.bucket4j.grid.coherence.CoherenceProcessor</class-name>
            <serializer>
                <class-name>io.github.bucket4j.grid.coherence.pof.CoherenceEntryProcessorPofSerializer</class-name>
            </serializer>
        </user-type>
    </user-type-list>
</pof-config>
----
Double-check with https://docs.oracle.com/cd/E24290_01/coh.371/e22837/api_pof.htm#COHDG5182[official Oracle Coherence documentation] in case of any questions related to ``Portable Object Format``.
