[[bucket4j-hazelcast, Bucket4j-Hazelcast]]
=== Hazelcast integration
==== Dependencies
To use Bucket4j extension for Hazelcast with ``Hazelcast 4.x`` you need to add the following dependency:
[source, xml, subs=attributes+]
----
<dependency>
    <groupId>com.bucket4j</groupId>
    <artifactId>bucket4j-hazelcast</artifactId>
    <version>{revnumber}</version>
</dependency>
----
If you are using a legacy version of Hazelcast ``4.x`` then you need to add the following dependency:
[source, xml, subs=attributes+]
----
<dependency>
    <groupId>com.bucket4j</groupId>
    <artifactId>bucket4j-hazelcast-4</artifactId>
    <version>{revnumber}</version>
</dependency>
----
NOTE: see https://github.com/bucket4j/bucket4j/tree/8.0#java-compatibility-matrix[Java compatibility matrix] if you need for build that is compatible with Java 8

==== General compatibility matrix principles:
* Bucket4j authors do not perform continuous monitoring of new Hazelcast releases. So, there is can be a case when there is no one version of Bucket4j which is compatible with the newly released Hazelcast,
just log an issue to https://github.com/bucket4j/bucket4j/issues[bug tracker] in this case, adding support to new version of Hazelcast is usually an easy exercise.
* Integrations with legacy versions of Hazelcast are not removed without a clear reason. Hence You are in safety, even you are working in a big enterprise company that does not update its infrastructure frequently because You still get new Bucket4j's features even for legacy Hazelcast's releases.

==== Example of Bucket instantiation
[source, java]
----
IMap<K, byte[]> map = ...;
private static final HazelcastProxyManager<K> proxyManager = Bucket4jHazelcast
    .entryProcessorBasedBuilder(map)
     // setup optional parameters if necessary
    .build();

...
BucketConfiguration configuration = BucketConfiguration.builder()
    .addLimit(limit -> limit.capacity(1_000).refillGreedy(1_000, ofMinutes(1)))
    .build();

Bucket bucket = proxyManager.builder().build(key, configuration);
----

==== Configuring flexible per entry expiration
It is possible configure precise expiration for bucket entries inside cache,
in order to avoid storing data related to buckets more than it needs to refill for consumed tokens.
[source, java]
----
IMap<K, byte[]> map = ...;
Duration evictionJitter = Duration.ofSeconds(15);
ExpirationAfterWriteStrategy expiration = ExpirationAfterWriteStrategy.basedOnTimeForRefillingBucketUpToMax(evictionJitter)

private static final HazelcastProxyManager<K> proxyManager = Bucket4jHazelcast
    .entryProcessorBasedBuilder(map)
    .expirationAfterWrite(expiration)
     // setup optional parameters if necessary
    .build();
----
How to choose eviction jitter properly? Zero means immediate eviction after refill,
however it is better to avoid too small jitter, because recreation of bucket after expiration will require one network hope,
so it is better to configure at least of few seconds for jitter in order to avoid to frequent buckets recreation.

==== Configuring Custom Serialization for Bucket4j library classes
If you configure nothing, then by default Java serialization will be used for serialization Bucket4j library classes. Java serialization can be rather slow and should be avoided in general.
``Bucket4j`` provides https://docs.hazelcast.org/docs/3.0/manual/html/ch03s03.html[custom serializers] for all library classes that could be transferred over the network.

To let Hazelcast know about fast serializers you should register them programmatically in the serialization config:
[source, java]
----
import com.hazelcast.config.Config;
import com.hazelcast.config.SerializationConfig;
import com.hazelcast.config.SerializerConfig;
import io.github.bucket4j.grid.hazelcast.serialization.HazelcastSerializer;
...
    Config config = ...
    SerializationConfig serializationConfig = config.getSerializationConfig();

    // the starting type ID number for Bucket4j classes.
    // you free to choose any unused ID, but be aware that Bucket4j uses 2 types currently,
    // and may use more types in the future, so leave enough empty space after baseTypeIdNumber
    int baseTypeIdNumber = 10000;

    HazelcastProxyManager.addCustomSerializers(serializationConfig, baseTypeIdNumber);
----

==== Configuring Custom Serialization using an Hazelcast standalone cluster
In case the Hazelcast Cluster is running as a standalone cluster outside your application, maybe started directly using its own jar or hosted by a third party software, you are not in position to register the custom serializers programmatically.

In order to let the hazelcast cluster be aware of the custom serialization the following 3 actions are required:

  1. Add the Bucket4j jars (`bucket4j-core` and `bucket4j-hazelcast`) into the classpath of each node of the Hazelcast cluster
  2. Declare the typeIdBase via **OS Environment Variable** or via **Java System Property**, in both case the name is: `bucket4j.hazelcast.serializer.type_id_base`. Of course the value provided here at the Hazelcast server side has to be the same used programmatically into your java code at hazelcast client side.
  3. Configure the custom serializers into the Hazlecast server configuration file, see the following hazelcast config snippet as reference:

[source,yaml]
----
# ----- Hazelcast SERIALIZATIONs configuration -----
serialization:
  serializers:
    - type-class: io.github.bucket4j.grid.hazelcast.HazelcastEntryProcessor
      class-name: io.github.bucket4j.grid.hazelcast.serialization.HazelcastEntryProcessorSerializer
    - type-class: io.github.bucket4j.grid.hazelcast.SimpleBackupProcessor
      class-name: io.github.bucket4j.grid.hazelcast.serialization.SimpleBackupProcessorSerializer
    - type-class: io.github.bucket4j.grid.hazelcast.HazelcastOffloadableEntryProcessor
      class-name: io.github.bucket4j.grid.hazelcast.serialization.HazelcastOffloadableEntryProcessorSerializer
----

==== Support for externally managed Hazelcast without classpath access
`bucket4j-hazelcast` requires putting Bucket4j jars to classpath of each node of Hazelcast cluster.
Sometimes you have no control over classpath because the Hazelcast cluster is externally managed(Paas scenario).
In such cases ```HazelcastProxyManager``` can not be used because it is implemented on top of https://docs.hazelcast.com/imdg/4.2/computing/entry-processor[EntryProcessor] functionality.

.Bucket4j provides two alternatives for PaaS topology:
HazelcastLockBasedProxyManager:: is implemented on top IMap methods `lock`, `get`, `put`, `unlock`.
This implementation always requires 4 network hops for one rate-limit check.

HazelcastCompareAndSwapBasedProxyManager:: is implemented on top IMap methods `get`, `replace`, `putIfAbsent`.
This implementation requires 2 network hops if no contention happens, but in case of high contention on the key amount of hops is unpredictable.

.Limitations of HazelcastLockBasedProxyManager and HazelcastCompareAndSwapBasedProxyManager
* `HazelcastLockBasedProxyManager` does not provide async API because of lack of `lockAsync` and `unlockAsync`  methods inside IMap API.
* `HazelcastCompareAndSwapBasedProxyManager` does not provide async API because lack of `replaceAsync` and `putIfAbsentAsync` methods inside IMap API.

If you wish to async API be supported by `HazelcastLockBasedProxyManager` and `HazelcastCompareAndSwapBasedProxyManager` ask Hazelcast maintainers to support the missed APIs mentioned above.

==== Known issues related with Docker and(or) SpringBoot
* https://github.com/bucket4j/bucket4j/discussions/186[#186 HazelcastEntryProcessor class not found] - check file permissions inside your image.
* https://github.com/bucket4j/bucket4j/issues/162[#182 HazelcastSerializationException with Hazelcast 4.2] - properly setup classloader for Hazelcast client configuration.
