[[bucket4j-infinispan, Bucket4j-Infinispan]]
==== Infinispan integration
===== Dependencies
To use ``bucket4j-infinispan`` with ``Infinispan 9.x/10.x``, add the following dependency:
[source, xml, subs=attributes+]
----
<dependency>
    <groupId>com.bucket4j</groupId>
    <artifactId>bucket4j_jdk17-infinispan</artifactId>
    <version>{revnumber}</version>
</dependency>
----

===== General compatibility matrix principles
* Bucket4j's authors do not continuously monitor new Infinispan releases, so there can be periods when no Bucket4j version is compatible with a newly released Infinispan version.
Log an issue in the https://github.com/bucket4j/bucket4j/issues[bug tracker] if you hit this - adding support for a new Infinispan version is usually an easy fix.
* Integrations with legacy Infinispan versions are not removed without a clear reason. Even if you work at a large enterprise that does not update its infrastructure often, you still get Bucket4j's new features on legacy Infinispan releases.


===== Special notes for Infinispan 10.0+
As mentioned in the https://infinispan.org/docs/dev/titles/developing/developing.html#marshalling[Infinispan Marshalling documentation], since release ``10.0.0`` Infinispan no longer allows deserialization of custom payloads into Java classes. If you do not configure serialization (as described below), any attempt to use Bucket4j with a recent Infinispan release will fail with an error like this:
[source, bash]
----
Jan 02, 2020 4:57:56 PM org.infinispan.marshall.persistence.impl.PersistenceMarshallerImpl objectToBuffer
WARN: ISPN000559: Cannot marshall 'class io.github.bucket4j.grid.infinispan.InfinispanProcessor'
java.lang.IllegalArgumentException: No marshaller registered for Java type io.github.bucket4j.grid.infinispan.SerializableFunctionAdapter
   at org.infinispan.protostream.impl.SerializationContextImpl.getMarshallerDelegate(SerializationContextImpl.java:279)
   at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:240)
   at org.infinispan.protostream.ProtobufUtil.toWrappedStream(ProtobufUtil.java:196)
----
There are three ways to solve this problem:
* Configure JBoss Marshalling instead of the default ProtoStream marshaller, as described https://infinispan.org/docs/dev/titles/developing/developing.html#jboss_marshalling[here].
* Configure the Java Serialization Marshaller instead of the default ProtoStream marshaller, as described https://infinispan.org/docs/dev/titles/developing/developing.html#java_serialization_marshaller[here].
Do not forget to add the ``io.github.bucket4j.*`` regexp to the allowlist if you choose this option.
* Or (recommended) simply register the ``Bucket4j serialization context initializer`` in the serialization configuration.
This can be done either programmatically or declaratively:

.Programmatic registration of Bucket4jProtobufContextInitializer
[source, java]
----
import io.github.bucket4j.grid.infinispan.serialization.Bucket4jProtobufContextInitializer;
import org.infinispan.configuration.global.GlobalConfigurationBuilder;
...
GlobalConfigurationBuilder builder = new GlobalConfigurationBuilder();
builder.serialization().addContextInitializer(new Bucket4jProtobufContextInitializer());
----

.Declarative registration of Bucket4jProtobufContextInitializer
[source, xml]
----
<serialization>
    <context-initializer class="io.github.bucket4j.grid.infinispan.serialization.Bucket4jProtobufContextInitializer"/>
</serialization>
----
That's it - registering ``Bucket4jProtobufContextInitializer`` in either way is enough to make Bucket4j compatible with the ProtoStream marshaller. You do not need to worry about ``*.proto`` files, annotations, or allowlists; all the necessary Protobuf configuration is generated by ``Bucket4jProtobufContextInitializer`` and registered on the fly.

===== Example of Bucket instantiation for EmbeddedCacheManager
[source, java]
----
org.infinispan.functional.FunctionalMap.ReadWriteMap<K, byte[]> map = ...;
private static final InfinispanProxyManager<K> proxyManager = Bucket4jInfinispan
    .entryProcessorBasedBuilder(map)
     // setup optional parameters if necessary
    .build();
...
BucketConfiguration configuration = BucketConfiguration.builder()
    .addLimit(limit -> limit.capacity(1_000).refillGreedy(1_000, ofMinutes(1)))
    .build();

Bucket bucket = proxyManager.getProxy(key, () -> configuration);
----

===== Example of Bucket instantiation for RemoteCacheManager (Hot Rod client)
[source, java]
----
org.infinispan.client.hotrod.RemoteCache<K, byte[]> remoteCache = ...;
private static final InfinispanProxyManager<K> proxyManager = Bucket4jInfinispan
    .hotrodClientBasedBuilder(remoteCache)
     // setup optional parameters if necessary
    .build();
...
BucketConfiguration configuration = BucketConfiguration.builder()
    .addLimit(limit -> limit.capacity(1_000).refillGreedy(1_000, ofMinutes(1)))
    .build();

Bucket bucket = proxyManager.getProxy(key, () -> configuration);
----